/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'evgeny' at '29/06/17 11:19 AM' with Gradle 2.5
 *
 * @author evgeny, @date 29/06/17 11:19 AM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
